module.exports = [
  {
    id: "radio94-video-2026",
    permalink: "/press/fotografija-postojne-iz-zraka-in-pod-zemljo/index.html",
    title: "Fotografija Postojne iz zraka in pod zemljo",
    publication: "Radio 94",
    section: "Video interview",
    date: "2026",
    displayDate: "2026",
    youtubeId: "TYeM4MJ5kCQ",
    summary: "A Radio 94 conversation about photographing Postojna from the air and below ground.",
    originalUrl: "https://www.youtube.com/watch?v=TYeM4MJ5kCQ",
    originalLabel: "Watch on YouTube"
  },
  {
    id: "prepih-2024",
    permalink: "/press/prepih-na-obisku-zan-kafol/index.html",
    title: "Prepih na obisku: Žan Kafol",
    publication: "Prepih",
    section: "Interview",
    date: "2024",
    displayDate: "April 2024",
    image: "/assets/images/press-prepih-2024.jpg",
    imageAlt: "Žan Kafol in the Prepih interview",
    imageCaption: "Prepih na obisku · April 2024",
    summary: "A full interview about aerial photography, caves, karst landscapes and the work behind the photographs.",
    originalUrl: "https://www.postojna.si/objava/910480",
    originalLabel: "Read the original interview"
  },
  {
    id: "rtvslo-creative-2023",
    permalink: "/press/da-si-lahko-zares-ustvarjalen/index.html",
    title: "Da si lahko zares ustvarjalen, moraš včasih kršiti ustaljene okvire",
    publication: "RTV Slovenija",
    section: "Interview",
    date: "2023",
    displayDate: "2023",
    image: "/assets/images/press-rtvslo-creative.jpg",
    imageAlt: "RTV Slovenija interview with Žan Kafol",
    imageCaption: "RTV Slovenija · Interview, 2023",
    summary: "An RTV Slovenija interview about creative decisions, established conventions and finding a personal photographic approach.",
    originalUrl: "https://www.rtvslo.si/zabava-in-slog/ture-avanture/da-si-lahko-zares-ustvarjalen-moras-vcasih-krsiti-ustaljene-okvire/691924",
    originalLabel: "Read at RTV Slovenija"
  },
  {
    id: "rtvslo-amateur-2023",
    permalink: "/press/ce-si-amater-se-ne-pomeni-da-si-slab/index.html",
    title: "Če si amater, še ne pomeni, da si slab",
    publication: "RTV Slovenija",
    section: "Interview",
    date: "2023",
    displayDate: "2023",
    image: "/assets/images/press-rtvslo-interview.jpg",
    imageAlt: "RTV Slovenija interview with Žan Kafol",
    imageCaption: "RTV Slovenija · Interview, 2023",
    summary: "A conversation about photography outside a commercial practice, awarded work and the value of sustained amateur work.",
    originalUrl: "https://www.rtvslo.si/kultura/vizualna-umetnost/ce-si-amater-se-ne-pomeni-da-si-slab-meni-veckrat-nagrajeni-fotograf-zan-kafol/689184",
    originalLabel: "Read at RTV Slovenija"
  },
  {
    id: "dobro-jutro-2023",
    permalink: "/press/dvakratni-zmagovalec-national-geographica/index.html",
    title: "Dvakratni zmagovalec National Geographica",
    publication: "Dobro jutro, RTV Slovenija",
    section: "Television interview",
    date: "2023",
    displayDate: "2023",
    youtubeId: "PE-eHr3zWnk",
    summary: "A studio conversation following the second overall National Geographic Slovenia photo-competition win.",
    originalUrl: "https://www.youtube.com/watch?v=PE-eHr3zWnk",
    originalLabel: "Watch on YouTube"
  },
  {
    id: "nedelo-2023",
    permalink: "/press/ce-se-hoces-umakniti-gres-gor-ali-pa-dol/index.html",
    title: "Če se hočeš umakniti, greš gor ali pa dol",
    publication: "neDelo",
    section: "Fenomeni",
    date: "2023-10-21",
    displayDate: "October 21, 2023 · Print, page 18",
    byline: "Grega Kališnik",
    summary: "A neDelo profile connecting flight, cave exploration and photography.",
    originalUrl: "https://www.delo.si/nedelo/ce-se-hoces-umakniti-gres-gor-ali-pa-dol",
    originalLabel: "Read the online article at Delo",
    scan: "/assets/images/press-nedelo.jpg",
    scanAlt: "Full-page scan of the neDelo interview with Žan Kafol"
  },
  {
    id: "radio94-natgeo-2023",
    permalink: "/press/zanu-kafolu-se-je-v-poletni-noci-vse-poklopilo/index.html",
    title: "Žanu Kafolu se je v poletni noči vse poklopilo",
    publication: "Radio 94",
    section: "Radio interview",
    date: "2023",
    displayDate: "2023",
    image: "/assets/images/press-radio94-natgeo-2023.jpg",
    imageAlt: "Radio 94 coverage of Žan Kafol's 2023 National Geographic recognition",
    imageCaption: "Radio 94 · 2023",
    summary: "Radio 94 coverage of Enlightened (All Roads Lead to Rakov Škocjan) and the 2023 National Geographic Slovenia win.",
    originalUrl: "https://www.radio94.si/zanu-kafolu-se-je-v-poletni-noci-vse-poklopilo/",
    originalLabel: "Listen at Radio 94"
  },
  {
    id: "primorska-kronika-2023",
    permalink: "/press/razsvetljenje-v-rakovem-skocjanu/index.html",
    title: "Razsvetljenje v Rakovem Škocjanu",
    publication: "Primorska kronika, TV Koper",
    section: "Television report",
    date: "2023",
    displayDate: "2023",
    youtubeId: "OrNQ_4JSaoY",
    summary: "A Primorska kronika report on the award-winning photograph made beneath the Little Natural Bridge in Rakov Škocjan.",
    originalUrl: "https://www.youtube.com/watch?v=OrNQ_4JSaoY",
    originalLabel: "Watch on YouTube"
  },
  {
    id: "prvi-dnevnik-2023",
    permalink: "/press/znova-izbranec-national-geographica/index.html",
    title: "Znova izbranec National Geographica",
    publication: "Prvi dnevnik, RTV Slovenija",
    section: "Television report",
    date: "2023",
    displayDate: "2023",
    youtubeId: "fw4Psa0lcx0",
    summary: "A Prvi dnevnik report on Žan Kafol's second overall National Geographic Slovenia photo-competition win.",
    originalUrl: "https://www.youtube.com/watch?v=fw4Psa0lcx0",
    originalLabel: "Watch on YouTube"
  },
  {
    id: "na-soncni-strani-2023",
    permalink: "/press/na-soncni-strani/index.html",
    title: "Žan Kafol: Na sončni strani",
    publication: "TV Koper, RTV Slovenija",
    section: "Television interview",
    date: "2023",
    displayDate: "2023",
    youtubeId: "bkEhJ0gXGU4",
    summary: "A television conversation for Na sončni strani focused entirely on paragliding.",
    originalUrl: "https://www.youtube.com/watch?v=bkEhJ0gXGU4",
    originalLabel: "Watch on YouTube"
  },
  {
    id: "prepih-2022",
    permalink: "/press/zan-kafol-od-zgoraj-od-blizu/index.html",
    title: "Žan Kafol: od zgoraj, od blizu",
    publication: "Postojnski prepih",
    section: "Zanimivosti",
    date: "2022-11",
    displayDate: "November 2022 · Issue 134, page 20",
    byline: "Jaka Zalar",
    photoCredit: "Mitja Lutar",
    summary: "A Prepih feature about the aerial and close-range perspectives in Žan Kafol's photography.",
    originalUrl: "https://www.postojna.si/Files/eMagazine/105/702287/Prepih%20November%2021c-11-22%20WEB.pdf",
    originalLabel: "Open the complete Prepih issue",
    scan: "/assets/images/press-prepih-2022-article.jpg",
    scanAlt: "Scan of the Prepih article Žan Kafol: od zgoraj, od blizu"
  },
  {
    id: "radio94-nedeljski-2022",
    permalink: "/press/nedeljski-klepet-zan-kafol/index.html",
    title: "Nedeljski klepet: Žan Kafol",
    publication: "Radio 94",
    section: "Radio interview",
    date: "2022",
    displayDate: "2022",
    image: "/assets/images/press-radio94-nedeljski.jpg",
    imageAlt: "Nedeljski klepet with Žan Kafol on Radio 94",
    imageCaption: "Radio 94 · Nedeljski klepet, 2022",
    summary: "A Sunday conversation on Radio 94 about photography, paragliding, caves and Postojna.",
    originalUrl: "https://www.radio94.si/nedeljski-klepet-zan-kafol/",
    originalLabel: "Listen at Radio 94"
  },
  {
    id: "radio94-natgeo-2022",
    permalink: "/press/zan-kafol-zmagal-na-natecaju-national-geographica/index.html",
    title: "Žan Kafol zmagal na natečaju National Geographica",
    publication: "Radio 94",
    section: "Radio interview",
    date: "2022",
    displayDate: "2022",
    image: "/assets/images/press-radio94-natgeo-2022.jpg",
    imageAlt: "Radio 94 coverage of Žan Kafol's 2022 National Geographic win",
    imageCaption: "Radio 94 · 2022",
    summary: "Radio 94 coverage of Cerkniško polje and the 2022 National Geographic Slovenia photo-competition win.",
    originalUrl: "https://www.radio94.si/zan-kafol-zmagal-na-natecaju-national-geographica/",
    originalLabel: "Listen at Radio 94"
  }
];
