module.exports = {
  en: {
    common: {
      menu: "Menu",
      primaryNavigation: "Primary navigation",
      nav: { work: "Work", about: "About", featured: "Featured", press: "Press", contact: "Contact" },
      home: "Home",
      switchLabel: "SL",
      switchAria: "Switch to Slovenian",
      skip: "Skip to content",
      contact: "Contact",
      follow: "Follow",
      footerText: "Photo stories shaped by flight,<br>caves and the karst landscape.",
      backToTop: "Back to top ↑",
      backHome: "Back home ↑"
    },
    home: {
      title: "Žan Kafol — Aerial & Cave Photographer",
      metaDescription: "Aerial, cave and nature photo stories by Žan Kafol, a photographer and software engineer based in Postojna, Slovenia.",
      heroKicker: "Stories in two directions",
      heroTitle: "Aerial &amp; cave<br>photography",
      heroIntro: "Photo stories shaped by flight,<br>caves and the karst landscape.",
      explore: "Explore",
      selectedWorks: "Selected works",
      about: "About",
      portraitAlt: "Portrait of Žan Kafol",
      aboutLead: "I’m a photographer and software engineer based in Postojna, Slovenia.",
      aboutText: "Photography grew alongside paragliding and caving. The camera moves between long views from the air, the darkness of the karst and night landscapes close to home.",
      moreStories: "More photo stories",
      facts: {
        location: "Location",
        locationText: "Postojna<br>Slovenia",
        institute: "Institute",
        instituteText: "Karst Research Institute<br>ZRC SAZU",
        practice: "Photography practice",
        practiceText: "Aerial, cave, nature<br>and night photography"
      },
      featured: "Featured & awarded",
      publicationsAria: "Selected publications",
      publishedIn: "Published in",
      press: "Press & interviews",
      previousPress: "Previous press page",
      nextPress: "Next press page",
      journal: "Blog posts",
      allPosts: "All posts"
    },
    gallery: {
      titleSuffix: "Žan Kafol",
      selectedWorks: "Selected works",
      photographs: "photographs",
      categoriesAria: "Photography collections",
      galleryAria: "photographs",
      slovenianTitle: "Slovenian title",
      archive: "View archived National Geographic publication",
      open: "Open",
      lightbox: "Image viewer",
      close: "Close",
      previous: "Previous photograph",
      next: "Next photograph"
    },
    press: {
      archiveTitle: "Press & interviews — Žan Kafol",
      archiveMeta: "Interviews, television appearances, radio conversations and published features with Žan Kafol.",
      archiveLabel: "Press archive",
      archiveHeading: "Press &amp;<br>interviews",
      archiveIntro: "Television appearances, radio conversations and published profiles covering photography, paragliding, caves and the karst landscape.",
      listingAria: "Press and interview features",
      kinds: { video: "Video", audio: "Radio", award: "Recognition", article: "Article" },
      viewFeature: "View feature",
      back: "← Press & interviews",
      wordsBy: "Words by",
      photographyBy: "Photography by",
      openPage: "Open page",
      articleScan: "of the article scan at full size",
      publishedIn: "Published in",
      page: "Page",
      of: "of",
      openScan: "Open article scan at full size",
      openFull: "Open the scan at full size"
    },
    featured: {
      back: "← Featured & awarded",
      label: "Featured & awarded",
      openImage: "Open image at full size"
    }
  },
  sl: {
    common: {
      menu: "Meni",
      primaryNavigation: "Glavna navigacija",
      nav: { work: "Delo", about: "O meni", featured: "Dosežki", press: "Mediji", contact: "Kontakt" },
      home: "Domov",
      switchLabel: "EN",
      switchAria: "Preklopi na angleščino",
      skip: "Preskoči na vsebino",
      contact: "Kontakt",
      follow: "Spremljaj",
      footerText: "Fotografske zgodbe, ki jih oblikujejo letenje,<br>jame in kraška pokrajina.",
      backToTop: "Nazaj na vrh ↑",
      backHome: "Nazaj domov ↑"
    },
    home: {
      title: "Žan Kafol — zračni in jamski fotograf",
      metaDescription: "Zračne, jamske in naravoslovne fotografske zgodbe Žana Kafola, fotografa in programskega inženirja iz Postojne.",
      heroKicker: "Zgodbe v dveh smereh",
      heroTitle: "Zračna in jamska<br>fotografija",
      heroIntro: "Fotografske zgodbe, ki jih oblikujejo letenje,<br>jame in kraška pokrajina.",
      explore: "Razišči",
      selectedWorks: "Izbrana dela",
      about: "O meni",
      portraitAlt: "Portret Žana Kafola",
      aboutLead: "Sem fotograf in programski inženir iz Postojne.",
      aboutText: "Fotografija se je razvijala ob jadralnem padalstvu in jamarstvu. Motivom sledim od širokih pogledov iz zraka do teme kraškega podzemlja in nočnih pokrajin v bližini doma.",
      moreStories: "Več fotografskih zgodb",
      facts: {
        location: "Lokacija",
        locationText: "Postojna<br>Slovenija",
        institute: "Inštitut",
        instituteText: "Inštitut za raziskovanje krasa<br>ZRC SAZU",
        practice: "Fotografsko delo",
        practiceText: "Zračna, jamska, naravoslovna<br>in nočna fotografija"
      },
      featured: "Objave in nagrade",
      publicationsAria: "Izbrane objave",
      publishedIn: "Objavljeno v",
      press: "Mediji in intervjuji",
      previousPress: "Prejšnja stran medijskih objav",
      nextPress: "Naslednja stran medijskih objav",
      journal: "Zapisi na blogu",
      allPosts: "Vsi zapisi"
    },
    gallery: {
      titleSuffix: "Žan Kafol",
      selectedWorks: "Izbrana dela",
      photographs: "fotografij",
      categoriesAria: "Fotografske zbirke",
      galleryAria: "fotografije",
      slovenianTitle: "Slovenski naslov",
      archive: "Poglej arhivirano objavo National Geographic",
      open: "Odpri",
      lightbox: "Pregledovalnik fotografij",
      close: "Zapri",
      previous: "Prejšnja fotografija",
      next: "Naslednja fotografija"
    },
    press: {
      archiveTitle: "Mediji in intervjuji — Žan Kafol",
      archiveMeta: "Intervjuji, televizijski in radijski pogovori ter objavljeni prispevki z Žanom Kafolom.",
      archiveLabel: "Medijski arhiv",
      archiveHeading: "Mediji in<br>intervjuji",
      archiveIntro: "Televizijski nastopi, radijski pogovori in objavljeni portreti o fotografiji, jadralnem padalstvu, jamah in kraški pokrajini.",
      listingAria: "Medijski prispevki in intervjuji",
      kinds: { video: "Video", audio: "Radio", award: "Priznanje", article: "Članek" },
      viewFeature: "Poglej prispevek",
      back: "← Mediji in intervjuji",
      wordsBy: "Besedilo",
      photographyBy: "Fotografija",
      openPage: "Odpri stran",
      articleScan: "članka v polni velikosti",
      publishedIn: "Objavljeno v",
      page: "Stran",
      of: "od",
      openScan: "Odpri posnetek članka v polni velikosti",
      openFull: "Odpri posnetek v polni velikosti"
    },
    featured: {
      back: "← Objave in nagrade",
      label: "Objave in nagrade",
      openImage: "Odpri fotografijo v polni velikosti"
    }
  }
};
